// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmhqkvjsuwpeathoomvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtaHFrdmpzdXdwZWF0aG9vbXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NzA4NzIsImV4cCI6MjA2NTA0Njg3Mn0.ytNErpeg3v26ICaYHUZa4SW3xTzKS1K84lJdZHxErbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);